artifacts_root: "artifacts"

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://github.com/rkdsai/walmart-sales/raw/refs/heads/main/raw_data.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  data_dirs:
    features: artifacts/data_ingestion/features.csv
    stores: artifacts/data_ingestion/stores.csv
    train: artifacts/data_ingestion/train.csv
    test: artifacts/data_ingestion/test.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_dirs:
    features: artifacts/data_ingestion/features.csv
    stores: artifacts/data_ingestion/stores.csv
    train: artifacts/data_ingestion/train.csv
    test: artifacts/data_ingestion/test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/final_train_data.csv
  test_data_path: artifacts/data_transformation/final_test_data.csv
  pipeline_name: regressor_pipeline.pkl
  model_instance_name: model.pkl
  target_column: Weekly_Sales

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/final_test_data.csv
  pipeline_path: artifacts/model_trainer/regressor_pipeline.pkl
  model_instance_path: artifacts/model_trainer/model.pkl
  metrics_file_name: artifacts/model_evaluation/metrics.json